#!/usr/bin/ansible-playbook -K
---
- hosts: localhost
  gather_facts: no
  vars:
    # Set this to yes if you want to overwrite any local dot configs
    force_overwrite: no
    # The base packages that should be installed
    dnf_pkgs_base:
      - htop
      - jq
      - neovim
      - python3
      - ripgrep
      - tmux
      - zsh
      - zsh-syntax-highlighting
    # The neovim config path (FIXME: I'd like to use $XDG_CONFIG, but not sure how)
    nvim_config_path: ~/.config/nvim/init.vim

  tasks:
    - name: Install base packages
      become: yes
      dnf:
        state: present
        name: "{{ dnf_pkgs_base }}"
    - name: Configure zsh
      copy:
        src: zsh/.zshrc
        dest: ~/.zshrc
        force: "{{ force_overwrite }}"
    - name: Configure tmux
      copy:
        src: tmux/.tmux.conf
        dest: ~/.tmux.conf
        force: "{{ force_overwrite }}"
    - name: Configure neovim (make sure its config exists)
      file:
        dest: "{{ nvim_config_path | dirname }}"
        state: directory
        recurse: yes
    - name: Configure neovim
      copy:
        src: vim/init.vim
        dest: "{{ nvim_config_path }}"
        force: "{{ force_overwrite }}"
